### ISSUE TITLE
implement trait std::ops::IndexMut for rblas::math::mat::Mat ?

### ISSUE THREAD

**Issue by snd** [mikkyang/rust-blas#15]
hey,

i’m considering using rblas to speed up [some machine learning code i’m working on](https://github.com/snd/onmf).
i’ve done some [benchmarks](https://github.com/snd/onmf/blob/master/benches/rblas_vs_nalgebra.rs).
unsurprisingly rblas is 4-10 times faster than the same operations in nalgebra.

i need to fill some [rblas::math::mat::Mat](https://mikkyang.github.io/rust-blas/doc/rblas/math/mat/struct.Mat.html) with data flexibly and programmatically.

unfortunately i've not found a nice way to do so.
maybe i’m missing something obvious ?

**it would be great if [rblas::math::mat::Mat](https://mikkyang.github.io/rust-blas/doc/rblas/math/mat/struct.Mat.html) implemented [std::ops::IndexMut](https://doc.rust-lang.org/stable/std/ops/trait.IndexMut.html).**
is there a specific reason why it doesn't at the moment or is this just an oversight ?

**i’d be happy to implement it and do a pull request !**

let me know.

best,
max

**Comment by mikkyang** [comment]
Hey Max,

The `math` mod was more of an experimental thing for me, seeing if I could implement some common operators over the traits to make it easier to use, but I didn't really envision it as something that should belong in a binding/wrapper library. 

I don't think that the library should ship with any `struct`s of its own, so I'm deprecating the sugared syntax soon.

Maybe with abstract return types, this could be solved, but in the meantime, you could check out a library like [ndarray](https://github.com/bluss/rust-ndarray) for operations like this. Thanks for your understanding!

**Comment by mikkyang** [comment]
Also [ndarray](https://github.com/bluss/rust-ndarray) has support for `rblas` through an optional feature, so you shouldn't be losing any performance.

**Comment by snd** [comment]
thanks for the quick response.

that’s great ! the integration with ndarray is a good solution for me.

> I don't think that the library should ship with any structs of its own

i completely agree.

it would be great if nalgebra were mentioned somewhere in the readme and/or documentation for rblas. if i’d been aware of the integration i wouldn’t have opened this issue. closing this.
